site_name: Starlette Bridge
site_description: The Starlette events bridge that you need.
site_url: https://starlette-bridge.tarsild.io

theme:
  name: "material"
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: "default"
      primary: "green"
      accent: "amber"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "purple"
      accent: "amber"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

repo_name: tarsil/starlette-bridge
repo_url: https://github.com/tarsil/starlette-bridge
edit_uri: ""
plugins:
  - search
  - markdownextradata:
      data: data

nav:
  - Starlette Bridge: "index.md"
  - Contributing: "contributing.md"
  - Sponsorship: "sponsorship.md"
  - Release Notes: "release-notes.md"
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html

extra:
  alternate:
    - link: /
      name: English
      lang: en
    # - link: /pt/
    #   name: Portuguese (Portugal)
    #   lang: en

extra_css:
  - statics/css/extra.css
  - statics/css/custom.css
